In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array((5, 6, 7, 8))
c = np.zeros((2, 3))
d = np.ones((3, 3))
e = np.eye(3)
f = np.arange(0, 10, 2)
g = np.linspace(0, 1, 5)

h = np.random.rand(3, 3)
i = np.random.randint(1, 10, (2, 2))

print(a, b, c, d, e, f, g)

[1 2 3 4] [5 6 7 8] [[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


In [4]:
print(a.shape, c.shape)
print(a.ndim, c.ndim)
print(a.size, c.size)
print(a.dtype)
a = a.astype(float)

(4,) (2, 3)
1 2
4 6
int64


In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [6]:
m = np.array([[1, 2], [3, 4]])
n = np.array([[5, 6], [7, 8]])

print(m + n)
print(m @ n)
print(np.dot(m, n))


[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [7]:
print(np.sum(m))
print(np.mean(m))
print(np.std(m))
print(np.min(m))
print(np.max(m))

print(np.sum(m, axis=0))
print(np.sum(m, axis=1))

10
2.5
1.118033988749895
1
4
[4 6]
[3 7]


In [8]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[::-1])


10
50
[20 30 40]
[50 40 30 20 10]


In [9]:
mat = np.array([[1, 2, 3], [4, 5, 6]])

print(mat[0, 1])
print(mat[:, 1])
print(mat[1, :])

2
[2 5]
[4 5 6]


In [10]:
reshaped = np.arange(12).reshape(3, 4)
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

ravelled = reshaped.ravel()
print(ravelled)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
stack1 = np.array([1, 2])
stack2 = np.array([3, 4])

print(np.vstack((stack1, stack2)))
print(np.hstack((stack1, stack2)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [12]:
split_arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(split_arr, 3))

broadcast_a = np.array([1, 2, 3])
broadcast_b = 2

print(broadcast_a + broadcast_b)

[array([1, 2]), array([3, 4]), array([5, 6])]
[3 4 5]


In [13]:
cond = np.array([1, 2, 3, 4, 5])
print(cond[cond > 2])

print(np.where(cond > 3, 1, 0))

[3 4 5]
[0 0 0 1 1]


In [14]:
rand_arr = np.random.randint(1, 100, 10)

print(np.sort(rand_arr))
print(np.unique(rand_arr))

print(np.argmax(rand_arr))
print(np.argmin(rand_arr))

print(np.cumsum(rand_arr))
print(np.cumprod(rand_arr))

[ 9 13 21 35 35 53 58 71 79 94]
[ 9 13 21 35 53 58 71 79 94]
4
1
[ 71  80 133 168 262 341 354 389 410 468]
[              71              639            33867          1185345
        111422430       8802371970     114430835610    4005079246350
   84106664173350 4878186522054300]


In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate((a, b)))

[1 2 3 4 5 6]


In [16]:
matrix = np.array([[1, 2], [3, 4]])

print(np.transpose(matrix))

inv = np.linalg.inv(matrix)
print(inv)

det = np.linalg.det(matrix)
print(det)

eigvals, eigvecs = np.linalg.eig(matrix)
print(eigvals)
print(eigvecs)

[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [17]:
data = np.array([1, 2, 3, 4, 5])

print(np.percentile(data, 50))
print(np.median(data))

print(np.clip(data, 2, 4))

print(np.log(data))
print(np.exp(data))
print(np.sqrt(data))

3.0
3.0
[2 2 3 4 4]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[1.         1.41421356 1.73205081 2.         2.23606798]
